# Generated by Django 5.0.2 on 2024-02-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_produitnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitnc',
            name='Duree_garantie',
            field=models.CharField(max_length=100),
        ),
    ]
